/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtesseract_JTesseract */

#ifndef _Included_jtesseract_JTesseract
#define _Included_jtesseract_JTesseract
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtesseract_JTesseract
 * Method:    initialise
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_initialise
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     jtesseract_JTesseract
 * Method:    setPageSegMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_setPageSegMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTesseract
 * Method:    setImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_setImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTesseract
 * Method:    getUTF8Text
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTesseract_getUTF8Text
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTesseract
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_clean
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTesseract
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_create
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTesseract
 * Method:    Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTesseract_Version
  (JNIEnv *, jclass);

/*
 * Class:     jtesseract_JTesseract
 * Method:    setFromBufferedImage
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTesseract_setFromBufferedImage
  (JNIEnv *env, jobject obj, jbyteArray data, jint rows, jint cols, jint channels);

#ifdef __cplusplus
}
#endif
#endif
