/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtesseract_JTessBaseAPI */

#ifndef _Included_jtesseract_JTessBaseAPI
#define _Included_jtesseract_JTessBaseAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    initialise
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_initialise
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setPageSegMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setPageSegMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getUTF8Text
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getUTF8Text
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_clean
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_create
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_Version
  (JNIEnv *, jclass);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setImageHelper
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setImageHelper
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    catchSignals
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_catchSignals
  (JNIEnv *, jclass);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setInputName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setInputName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getInputName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getInputName
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getSourceYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_getSourceYResolution
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getDatapath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getDatapath
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setOutputName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setOutputName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_setVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setDebugVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_setDebugVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getIntVariable
 * Signature: (Ljava/lang/String;Ljtesseract/JTessInt;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_getIntVariable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getBoolVariable
 * Signature: (Ljava/lang/String;Ljtesseract/JTessBoolean;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_getBoolVariable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getDoubleVariable
 * Signature: (Ljava/lang/String;Ljtesseract/JTessDouble;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_getDoubleVariable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getStringVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getStringVariable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    printVariables
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_printVariables
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getVariableAsString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_getVariableAsString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getInitLanguagesAsString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getInitLanguagesAsString
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getLoadedLanguagesAsVector
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jtesseract_JTessBaseAPI_getLoadedLanguagesAsVector
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getAvailableLanguagesAsVector
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jtesseract_JTessBaseAPI_getAvailableLanguagesAsVector
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    initLangMod
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_initLangMod
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    initForAnalysePage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_initForAnalysePage
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    readConfigFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_readConfigFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    readDebugConfigFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_readDebugConfigFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getPageSegMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_getPageSegMode
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    tesseractRect
 * Signature: ([BIIIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_tesseractRect
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    clearAdaptiveClassifier
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_clearAdaptiveClassifier
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setSourceResolution
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setSourceResolution
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getRegions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jtesseract_JTessBaseAPI_getRegions
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getThresholdedImageScaleFactor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_getThresholdedImageScaleFactor
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getTSVText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getTSVText
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getBoxText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getBoxText
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getUNLVText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getUNLVText
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    detectOrientationScript
 * Signature: ([I[FLjava/lang/String;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_detectOrientationScript
  (JNIEnv *, jobject, jintArray, jfloatArray, jstring, jfloatArray);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getOsdText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getOsdText
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    meanTextConf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_meanTextConf
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    allWordConfidences
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jtesseract_JTessBaseAPI_allWordConfidences
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_clear
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_end
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    clearPersistentCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_clearPersistentCache
  (JNIEnv *, jclass);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    isValidWord
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_isValidWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    isValidCharacter
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_isValidCharacter
  (JNIEnv *, jobject, jchar);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getTextDirection
 * Signature: ([I[F)Z
 */
JNIEXPORT jboolean JNICALL Java_jtesseract_JTessBaseAPI_getTextDirection
  (JNIEnv *, jobject, jintArray, jfloatArray);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getBlockTextOrientations
 * Signature: ([[I[[Z)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_getBlockTextOrientations
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    getUnichar
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtesseract_JTessBaseAPI_getUnichar
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    numDawgs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_numDawgs
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    oem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtesseract_JTessBaseAPI_oem
  (JNIEnv *, jobject);

/*
 * Class:     jtesseract_JTessBaseAPI
 * Method:    setMinOrientationMargin
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jtesseract_JTessBaseAPI_setMinOrientationMargin
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
